package io.mardom.ui.theme

import androidx.compose.ui.graphics.Color

object AppColors {
    object Light {
        val primary = Color(0xFF7A5900)
        val onPrimary = Color(0xFFFFFFFF)
        val primaryContainer = Color(0xFFFFDEA2)
        val onPrimaryContainer = Color(0xFF261900)
        val secondary = Color(0xFF6C5C3F)
        val onSecondary = Color(0xFFFFFFFF)
        val secondaryContainer = Color(0xFFF6E0BB)
        val onSecondaryContainer = Color(0xFF251A04)
        val tertiary = Color(0xFF4B6545)
        val onTertiary = Color(0xFFFFFFFF)
        val tertiaryContainer = Color(0xFFCDEBC3)
        val onTertiaryContainer = Color(0xFF092008)
        val error = Color(0xFFBA1A1A)
        val errorContainer = Color(0xFFFFDAD6)
        val onError = Color(0xFFFFFFFF)
        val onErrorContainer = Color(0xFF410002)
        val background = Color(0xFFFFFBFF)
        val onBackground = Color(0xFF1E1B16)
        val surface = Color(0xFFFFFBFF)
        val onSurface = Color(0xFF1E1B16)
        val surfaceVariant = Color(0xFFEDE1CF)
        val onSurfaceVariant = Color(0xFF4D4639)
        val outline = Color(0xFF7F7667)
        val inverseOnSurface = Color(0xFFF8EFE7)
        val inverseSurface = Color(0xFF34302A)
        val inversePrimary = Color(0xFFF4BE48)
        val shadow = Color(0xFF000000)
        val surfaceTint = Color(0xFF7A5900)
        val outlineVariant = Color(0xFFD1C5B4)
        val scrim = Color(0xFF000000)
    }

    object Dark {
        val primary = Color(0xFFF4BE48)
        val onPrimary = Color(0xFF402D00)
        val primaryContainer = Color(0xFF5C4200)
        val onPrimaryContainer = Color(0xFFFFDEA2)
        val secondary = Color(0xFFD9C4A0)
        val onSecondary = Color(0xFF3B2F15)
        val secondaryContainer = Color(0xFF53452A)
        val onSecondaryContainer = Color(0xFFF6E0BB)
        val tertiary = Color(0xFFB1CFA8)
        val onTertiary = Color(0xFF1E361B)
        val tertiaryContainer = Color(0xFF344D2F)
        val onTertiaryContainer = Color(0xFFCDEBC3)
        val error = Color(0xFFFFB4AB)
        val errorContainer = Color(0xFF93000A)
        val onError = Color(0xFF690005)
        val onErrorContainer = Color(0xFFFFDAD6)
        val background = Color(0xFF1E1B16)
        val onBackground = Color(0xFFE9E1D9)
        val surface = Color(0xFF1E1B16)
        val onSurface = Color(0xFFE9E1D9)
        val surfaceVariant = Color(0xFF4D4639)
        val onSurfaceVariant = Color(0xFFD1C5B4)
        val outline = Color(0xFF9A8F80)
        val inverseOnSurface = Color(0xFF1E1B16)
        val inverseSurface = Color(0xFFE9E1D9)
        val inversePrimary = Color(0xFF7A5900)
        val shadow = Color(0xFF000000)
        val surfaceTint = Color(0xFFF4BE48)
        val outlineVariant = Color(0xFF4D4639)
        val scrim = Color(0xFF000000)
    }

    val FlagGreen = Color(0xFF18a300)
    val FlagGold = Color(0xFFce9e32)
    val FlagGoldLighter = Color(0xFFF3BD0B)
    val FlagGoldDarker = Color(0xFF715b13)
    val FlagRed = Color(0xFFeb4034)
}
